### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by VMecko** [ph4r05/polynomial-distinguishers#1]
There is a problem with installation while running it from local directory using README.md instructions.

OS: Ubuntu 14.04 LTS
Processor: Intel® Core™ i5-3230M
Python version: Python 2.7.6
user: trazzy@Trazzy

Installation didn't find LAPACK/BLAS resources while installing scipy.
-numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

I resolved it by installing LAPACK
"sudo apt-get install libblas-dev liblapack-dev" with help of reply of user "hamx0r" from 
this source: https://askubuntu.com/questions/623578/installing-blas-and-lapack-packages

now the problem is with installation of fortran (recommended to install if i want to install scipy) : https://pastebin.com/uUvH4FCn  

when i run pip install for local dir by instructions from README.md i got the following error
Pastebin of installation command line: https://pastebin.com/v6SGSZgu
Pastebin of pip.log is huge (more than 512KB) so just the last part: https://pastebin.com/bMDxxcRE

When i try to install with "scipy installation with pip" from README.md the following error will occur: https://pastebin.com/dXFCVemj

**Comment by ph4r05** [comment]
@VMecko Try this

```bash
sudo apt-get update
sudo apt-get install gfortran python-pip build-essential libssl-dev swig libsasl2-dev libldap-dev python-dev
```

Then again

```
pip install scipy
```

**Comment by VMecko** [comment]
Thanks for suggestion. 

I completely uninstalled everything related to gfortran which solved the "unresolved dependencies" problem. Then i installed clean version of gfortran from source

`sudo apt-get install gfortran`

and that solved the problem.
