### ISSUE TITLE
Failure to install in Windows 10 via pip

### ISSUE THREAD

**Issue by petrs** [ph4r05/polynomial-distinguishers#4]
Hi, booltest will not install when installed via pip, happy to help with further debugging 

Command executed: 
`pip3 install booltest`

Error obtained:
 ```
...
Creating library build\temp.win-amd64-3.9\Release\bitarray\_bitarray.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\bitarray\_bitarray.cp39-win_amd64.exp
_bitarray.obj : error LNK2001: unresolved external symbol _PyObject_GC_UNTRACK
...
```

**Comment by ph4r05** [comment]
Which python version do you have?
It seems like 3.9, this version is not supported yet by the `bitarray` module. https://github.com/ph4r05/bitarray

**Comment by ph4r05** [comment]
https://docs.python.org/3/whatsnew/changelog.html

> bpo-35081: The _PyObject_GC_TRACK() and _PyObject_GC_UNTRACK() macros have been removed from the public C API.

**Comment by ph4r05** [comment]
@petrs try upgrading bitarray:
https://pypi.org/project/bitarray-ph4/1.6.2/

```bash
pip install bitarray-ph4==1.6.2
```

**Comment by petrs** [comment]
@ph4r05 thnak you, tried, but got 
 ```
pip-install-4_3sno7l\bitarray-ph4\setup.py", line 12, in <module>
data = open('bitarray/bitarray.h').read()
FileNotFoundError: [Errno 2] No such file or directory: 'bitarray/bitarray.h'
```

**Comment by ph4r05** [comment]
@petrs ok try again
```bash
pip install -U --no-cache bitarray-ph4==1.6.4
```

**Comment by petrs** [comment]
> 
> 
> Which python version do you have?
> It seems like 3.9, this version is not supported yet by the `bitarray` module. https://github.com/ph4r05/bitarray

yes, its 3.9

**Comment by petrs** [comment]
> 
> 
> @petrs ok try again
> 
> ```shell
> pip install -U --no-cache bitarray-ph4==1.6.4
> ```

yes, this one worked for me, thank you very much!

**Comment by petrs** [comment]
@ph4r05 So what is the right way to proceed further? Update readme? Add troubleshooting section?

**Comment by ph4r05** [comment]
I think it is done. The library is updated, it will be installed by default for new users.
